### ISSUE TITLE
WindFree Switch doesn't work

### ISSUE THREAD

**Issue by AppStudioLB** [igorxmath/homebridge-samsung-windfree-ac#8]
**Describe The Bug:**

If I check the WindFree mode switch in Apple Home, it says it doesn't respond. My Samsung AC model is AF16M7970GFN. Is this have different api call preference?

**To Reproduce:**

**Expected behavior:**

**Logs:**

```
This plugin threw an error from the characteristic 'On': Unhandled error thrown inside read handler for characteristic: Cannot read properties of undefined (reading 'acOptionalMode'). See https://homebridge.io/w/JtMGR for more info.
```
This log continuously appears.

**Plugin Config:**

```
{
    "name": "AC",
    "BaseURL": "https://api.smartthings.com/v1/",
    "AccessToken": "xxx-xxx-xxx-xxx-xxxx",
    "OptionalWindFreeSwitch": true,
    "platform": "Homebridge Samsung WindFree AC"
}
```

**Screenshots:**

**Environment:**

* **Plugin Version**: v1.0.4
* **Homebridge Version**: v1.8.2
* **Node.js Version**: v18.19.0
* **NPM Version**: v10.2.3
* **Operating System**: Raspbian

**Comment by igorxmath** [comment]
This model is not supported. Maybe there's a different custom capability for windFree mode.
